[package]
name = "GPMF-Parser"
version = "0.1.0"
edition = "2021"


[dev-dependencies]
anyhow = "1"

[dependencies]
thiserror = "1.0.61"
serde = { version = "1", features = ["derive"] }
config = { version = "0.11", features = ["toml"] }
clap = "3"
toml = { version = "0.5" }
gpmf-rs = { path = "./gpmf-rs" }#git clone https://github.com/jenslar/gpmf-rs.git