srs_dir_path    = "D:\\DEV\\RUST\\VIDEO_TEMP"
dest_dir_path   = "D:\\DEV\\RUST\\VIDEO_TEMP"
ffmpeg_dir_path = "D:\\DEV\\RUST\\VIDEO_TEMP"
output_file_postfix = "_FFCUT"

dep_time_correction = 2.0
time_start_offset = -60.0
time_end_offset = 3.0

min_accel_trigger = 50.0

